spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
server:
  port: 8081
  error.include-message: always

app:
  jwt:
    secret: phamdanghai

